### ISSUE TITLE
Local_Directory Veriable Path Configuration

### ISSUE THREAD

**Issue by sunilraskar** [Orasik/aws_lambda_ftp_function#1]
Thanks the code is really useful.  

The issue I am facing with code at the movement is how to set the variable - local_directory path. 

Please let me know how do I set the loca_directory variable. I am assuming it should be a root directory name under the configured bucket.

**Comment by orasik** [comment]
Hi, 
What did you try and  what was the error you got? The local directory in lambda will be /tmp as far as I remember
So if you want a writable directory this would be /tmp/folder_name

**Comment by sunilraskar** [comment]
I set the tmp local folder and the issue got resolved, but then it gave error at line

# **for file in files:**

files not defined. I am new to python. Please advise.

I trying to create a lambda function to download a zip file from a ftp site directly to a s3 bucket unzip the file and do bulk load in a local sql server db on a EC2 instance in a VPC.
